# Generated by Django 5.2.3 on 2025-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='id_conservation_status',
            new_name='conservation_status',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='id_habitats',
            new_name='habitat',
        ),
        migrations.RenameField(
            model_name='animals',
            old_name='id_species',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='habitats',
            old_name='id_section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='purchaseorders',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchaseorders',
            old_name='id_visit',
            new_name='visit',
        ),
        migrations.RenameField(
            model_name='ticketspurchaseorder',
            old_name='id_purchase_order',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='ticketspurchaseorder',
            old_name='id_ticket',
            new_name='ticket',
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='ticketspurchaseorder',
            unique_together={('ticket', 'purchase_order')},
        ),
    ]
