# Generated by Django 5.2.3 on 2025-06-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibicion',
            name='facts',
        ),
        migrations.CreateModel(
            name='ExhibicionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField(verbose_name='Exhibition Fact')),
                ('exhibicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.exhibicion')),
            ],
        ),
        migrations.AddField(
            model_name='exhibicion',
            name='facts',
            field=models.ManyToManyField(blank=True, related_name='exhibitions', to='api.exhibicionfacts', verbose_name='Exhibition Facts'),
        ),
    ]
