# Generated by Django 5.2.3 on 2025-06-16 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_exhibicion_facts_exhibicionfacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibicionimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Exhibition Image Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibicionimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Exhibition Image Updated At'),
        ),
    ]
