# Generated by Django 5.2.1 on 2025-05-27 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_province'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct')], max_length=30, unique=True, verbose_name='Conservation Status')),
            ],
            options={
                'verbose_name': 'Conservation Status',
                'verbose_name_plural': 'Conservation Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tickets_purchase_order',
            name='id_purchase_order',
        ),
        migrations.RemoveField(
            model_name='tickets_purchase_order',
            name='id_ticket',
        ),
        migrations.AlterModelOptions(
            name='animals',
            options={'ordering': ['name'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='habitats',
            options={'ordering': ['name'], 'verbose_name': 'Habitat', 'verbose_name_plural': 'Habitats'},
        ),
        migrations.AlterModelOptions(
            name='provinces',
            options={'ordering': ['name'], 'verbose_name': 'Province', 'verbose_name_plural': 'Provinces'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'ordering': ['name'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='visits',
            options={'ordering': ['-day'], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Animal Name'),
        ),
        migrations.AlterField(
            model_name='habitats',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='habitats',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Habitat Name'),
        ),
        migrations.AlterField(
            model_name='habitats',
            name='nums_animals',
            field=models.PositiveIntegerField(verbose_name='Number of Animals'),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Province Name'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='num_habitats',
            field=models.PositiveIntegerField(verbose_name='Number of Habitats'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Species Name'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ticket Name'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Price'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='day',
            field=models.DateField(verbose_name='Visit Day'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='occupied_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Occupied Slots'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='total_slots',
            field=models.PositiveIntegerField(default=1276, verbose_name='Total Slots'),
        ),
        migrations.AlterUniqueTogether(
            name='visits',
            unique_together={('day',)},
        ),
        migrations.AlterField(
            model_name='animals',
            name='id_conservation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.conservationstatus'),
        ),
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email', models.EmailField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('qr_image', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('id_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.visits')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketsPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('id_purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_purchase_order', to='api.purchaseorders')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_purchase_order', to='api.tickets')),
            ],
            options={
                'verbose_name': 'Tickets Purchase Order',
                'verbose_name_plural': 'Tickets Purchase Orders',
                'unique_together': {('id_ticket', 'id_purchase_order')},
            },
        ),
        migrations.DeleteModel(
            name='purchase_orders',
        ),
        migrations.DeleteModel(
            name='tickets_purchase_order',
        ),
        migrations.DeleteModel(
            name='conservation_status',
        ),
    ]
