# Generated by Django 5.2 on 2025-05-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='conservation_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('num_habitats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='purchase_orders',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickets_purchase_order',
            name='id_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_purchase_order', to='api.purchase_orders'),
        ),
        migrations.AlterField(
            model_name='tickets_purchase_order',
            name='id_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_purchase_order', to='api.tickets'),
        ),
        migrations.CreateModel(
            name='habitats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nums_animals', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitats', to='api.sections')),
            ],
        ),
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('id_conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.conservation_status')),
                ('id_habitats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.habitats')),
                ('id_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='api.species')),
            ],
        ),
    ]
