# Generated by Django 5.2.3 on 2025-06-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exhibicion_description_exhibiciondescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibicion',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='exhibicion',
            name='facts',
        ),
        migrations.RemoveField(
            model_name='exhibicion',
            name='images',
        ),
    ]
