# Generated by Django 5.2.1 on 2025-05-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_groups_userprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
