# Generated by Django 5.2.3 on 2025-06-17 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_exhibicion_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibicion',
            options={},
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='label',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='exhibicion',
            name='value',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='exhibiciondescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exhibicionfacts',
            name='fact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exhibicionimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exhibicionimage',
            name='image',
            field=models.ImageField(upload_to='exhibitions/'),
        ),
        migrations.AlterField(
            model_name='exhibicionimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ExhibicionButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
                ('link', models.URLField()),
                ('exhibicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='api.exhibicion')),
            ],
        ),
    ]
