# Generated by Django 5.2.3 on 2025-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_exhibicion_options_alter_exhibicion_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibicionbuttons',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
