# Generated by Django 5.2.3 on 2025-06-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_exhibicionbuttons_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibicionbuttons',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
