# Generated by Django 5.2.3 on 2025-06-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_exhibicionbuttons_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='programas/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.programaeducativo')),
            ],
        ),
    ]
