# Generated by Django 5.2.3 on 2025-06-18 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_programaeducativo_programaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosEducativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEducativosButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='api.servicioseducativos')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEducativosDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='api.servicioseducativos')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEducativosFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.servicioseducativos')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosEducativosImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibitions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicios_educativos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.servicioseducativos')),
            ],
        ),
    ]
