# Generated by Django 5.2.3 on 2025-06-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_servicioseducativos_servicioseducativosbuttons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioseducativos',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
