# Generated by Django 5.2.3 on 2025-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_servicioseducativos_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioseducativos',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='servicioseducativos',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
