# Generated by Django 5.2.3 on 2025-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_payment_payments_tickets_occupied_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
