# Generated by Django 5.2.3 on 2025-06-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='fecha',
            field=models.DateField(),
        ),
    ]
