# Generated by Django 5.2.3 on 2025-06-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_documents_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='tipo',
        ),
        migrations.AddField(
            model_name='documents',
            name='file_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
