# Generated by Django 5.2.3 on 2025-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_documents_file_size_alter_documents_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
