# Generated by Django 5.2.3 on 2025-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_documents_fecha_alter_documents_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='fecha',
            field=models.DateField(),
        ),
    ]
