# Generated by Django 5.2.3 on 2025-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_documents_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-fecha'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.FileField(upload_to='documentos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamaño del archivo'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
