# Generated by Django 5.2.3 on 2025-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_documents_options_alter_documents_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Máximo 500 caracteres', max_length=500, null=True),
        ),
    ]
