# Generated by Django 5.2.3 on 2025-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='total_crc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tickets',
            name='currency',
            field=models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], default='CRC', max_length=3),
        ),
    ]
