# Generated by Django 5.2.3 on 2025-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_purchaseorders_total_crc_purchaseorders_total_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], max_length=3)),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta'), ('PAYPAL', 'PayPal'), ('CASH', 'Efectivo/SINPE')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
